### PR TITLE
Story/rework ui4

### PR DESCRIPTION
**Pull request by erchiggins**

### CODE REVIEW

**Comment by fredbelotte** [comment]
carry on!

**Comment by fredbelotte** [comment]
how is it going?

**Comment by chiloflight21** [comment]
please merge with master. The conflicts above was resolved

**Comment by fredbelotte** [comment]
there are conflicts still!

**Comment by chiloflight21** [comment]
requesting a pull request to master

**Comment by fredbelotte** [comment]
all set!

**Pull request merged**
