### PR TITLE
story/continue-data-dev2

### PR DESCRIPTION
**Pull request by danielsmcelhaney**
I'll let you know when it's ready to merge, Fred!

### CODE REVIEW

**Comment by fredbelotte** [comment]
sounds good.

**Comment by danielsmcelhaney** [comment]
This branch is ready to be pulled. @fredbelotte

**Comment by fredbelotte** [comment]
there is a conflict, my friend.

**Comment by erchiggins** [comment]
Working on it! This branch will also remedy some issues.

**Comment by danielsmcelhaney** [comment]
It's really ready this time. lol!

**Comment by fredbelotte** [comment]
all done!

**Pull request merged**
