### PR TITLE
story/cont-data-dev

### PR DESCRIPTION
**Pull request by danielsmcelhaney**
Fred, I will let you know when this is ready to merge.

### CODE REVIEW

**Comment by danielsmcelhaney** [comment]
Sorry about appending the date to the branch name. I merged the branch with the user story name, but am continuing the work.  I didn't want to bother Emily for a new user story right now. I will fix it next time.

**Comment by fredbelotte** [comment]
that is ok @danielsmcelhaney.

**Comment by danielsmcelhaney** [comment]
Fred, We need this branch to be merged to Master.  I fixed some issues in the client. We now have data flow from database to client in this branch.

**Comment by danielsmcelhaney** [comment]
Will we be able to get this merged soon? We're meeting up at 3 today to continue our work.  It would be nice for this to be in Master by then. Thanks! @fredbelotte  @erchiggins @Ensworth

**Comment by fredbelotte** [comment]
all done!

**Pull request merged**
